### ISSUE TITLE
Unable to use fixed-lift analysis

### ISSUE THREAD

**Issue by maya-rn** [raalf/VAP3.0#6]
This line https://github.com/raalf/VAP3/blob/master/fcnXMLREAD.m#L48 gets overwritten by this block of code https://github.com/raalf/VAP3/blob/master/fcnXMLREAD.m#L355-L361. This is confusing me since it overwrites the initial read in from the input file. How can I run a fixed-lift analysis properly? Also, should the input file say 'True' and 'False' or '0' and '1'. Because based on these codes, it indicates that the input should be 'True' and 'False', but the ReadMe says '0' and '1'.

**Comment by travis-k** [comment]
Feature not a bug. Set VINF to nan. Everything is fine and good and great
